package org.app.bank.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;

@Entity
public class Account {
    // id is the primary key, autogenerated when the account is created
    private @Id @GeneratedValue Long id;
    private String name;
    private Double balance;

    // default constructor for JPA
    protected Account() {}

    public Account(String name, Double initialBalance) {
        this.name = name;
        this.balance = initialBalance;
    }

    public Long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public Double getBalance() {
        return balance;
    }

    public void setBalance(Double newBalance) {
        this.balance = newBalance;
    }
}